name: Update/Create Container on VPS

on:
  workflow_run:
    workflows: [ "Publish Docker image" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: publish-docker-image.push_to_registry

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure SSH Key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to VPS
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'docker-compose pull && docker-compose up -d'
